#!/python27/python
def side():
	print "<script>"
	print "function studin(){"
	print "document.getElementById('studsub').style.display='block';"
	print "}"
	print "function studout(){"
	print "document.getElementById('studsub').style.display='none';"
	print "}"
	print "function cin(){"
	print "document.getElementById('csub').style.display='block';"
	print "}"
	print "function cout(){"
	print "document.getElementById('csub').style.display='none';"
	print "}"
	print "function fin(){"
	print "document.getElementById('fsub').style.display='block';"
	print "}"
	print "function fout(){"
	print "document.getElementById('fsub').style.display='none';"
	print "}"
	print "</script>"
	print "<div class='container'>"
	print "<div class='header'>"
	print "<div class='lhead'>"
	print "<a href='#'><img src='../img_avatar2.png' alt='Insert Logo Here' name='Insert_logo' width='180' height='90' id='Insert_logo' style='background: #C6D580; display:block;' /></a>"
	print "</div>"
	print "<div class='rhead'>"
	print "<h1>College Management Systsem</h1>"
	print "</div>"
	print "<!-- end .header --></div>"
	print "<div class='sidebar1'>"
	print "<ul class='nav'>"
	print "<li><a href='homeadmin.html'>Home</a></li>"
	print "<li><a href='d1.py'>Department</a></li>"
	print "<li><a href='c1.py' onmouseover='cin()' onmouseleave='cout()'>Course</a></li>"
	print "<div class='modal' id='csub' onmouseover='cin()' onmouseleave='cout()'>"
	print "<ol class='nav'>"
	print "<li><a href='cdeptchoose.py'>Courses by Department</a></li>"
	print "</ol>"
	print "</div>"
	print "<li><a href='s1.py' onmouseover='studin()' onmouseleave='studout()'>Student</a></li>"
	print "<div class='modal' id='studsub' onmouseover='studin()' onmouseleave='studout()'>"
	print "<ol class='nav'>"
	print "<li><a href='sidchoose.py'>Student by ID</a></li>"
	print "<li><a href='sdeptchoose.py'>Students by Department</a></li>"
	print "<li><a href='sreq.py'>Student Requests</a></li>"
	print "</ol>"
	print "</div>"
	print "<li><a href='f1.py' onmouseover='fin()' onmouseleave='fout()'>Fees</a></li>"
	print "<div class='modal' id='fsub' onmouseover='fin()' onmouseleave='fout()'>"
	print "<ol class='nav'>"
	print "<li><a href='fsidchoose.py'>Fees by Student ID</a></li>"
	print "<li><a href='frepdate.py'>Fees Report</a></li>"
	print "<li><a href='freq.py'>Fees Requests</a></li>"
	print "</ol>"
	print "</div>"
	print "<li><a href='users.py'>Users</a></li>"
	print "<li><a href='../index.html'>Logout</a></li>"
	print "</ul>"
	print "<div style='height: auto'>"
	print "<p> College Management System is web application for managing day to day activity of the College</p>"
	print "</div>"
	print "<!-- end .sidebar1 --></div>"
